### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mcnesium** [matomo-org/matomo-log-analytics#158]
Sometimes I get this error messages while parsing the log file:

    Traceback (most recent call last):
     File "/home/me/www/analytics.mcnesium.com/misc/log-analytics/import_logs.py", line 2371, in <module>
       config = Configuration()
     File "/home/me/www/analytics.mcnesium.com/misc/log-analytics/import_logs.py", line 917, in __init__
       self._parse_args(self._create_parser())
     File "/home/me/www/analytics.mcnesium.com/misc/log-analytics/import_logs.py", line 897, in _parse_args
       self.options.piwik_token_auth = self._get_token_auth()
     File "/home/me/www/analytics.mcnesium.com/misc/log-analytics/import_logs.py", line 999, in _get_token_auth
       return credentials[1]
    IndexError: list index out of range

The following script gets log files via ssh from other servers and passes them on to the importer:

    PIWIKID="$1";
    USERHOST="$2";
    LOGFILE="$HOME/tmp/$USERHOST.log";
    PIWIKURL="https://analytics.mcnesium.com";
    IMPORTSCRIPT="$HOME/www/analytics.mcnesium.com/misc/log-analytics/import_logs.py";

    if scp -i "$HOME/.ssh/rsync_rsa" "$USERHOST:www/logs/access_log" "$LOGFILE" > /dev/null ; then
            if [ -s "$LOGFILE" ]; then      # if it's a non-empty file
                    PARAMS[0]="--url=$PIWIKURL";
                    PARAMS[1]="--enable-reverse-dns";
    #               PARAMS[2]="--enable-bots";
    #               PARAMS[3]="--enable-http-errors";
                    PARAMS[4]="--enable-http-redirects";
                    PARAMS[5]="--enable-static";
                    if /usr/bin/python "$IMPORTSCRIPT" $(printf '%s ' "${PARAMS[@]}") "--idsite=$PIWIKID" "$LOGFILE" > /dev/null ; then
                            # success
                            rm $LOGFILE;
                    else
                            # fail
                            KEEPLOGFILE="$(dirname $LOGFILE)/$(date +'%Y%m%d%H%M%S').log";
                            mv $LOGFILE $KEEPLOGFILE;
                    fi
            else
                    echo "$LOGFILE doesn't exist or has size zero.";
            fi
    fi

The above error message then comes via mail sent by the cron job. [The logfile created in this session can be downloaded here](https://mcnesium.com/tmp/20161103200006.log). Why is it doing this sometimes? The cron job runs hourly for multiple log files originating on different servers, pulling all of them into this piwik instance. Mails with those error messages appear randomly every other day, no pattern observable. Any ideas?

**Comment by mattab** [comment]
Sorry no idea. Does anyone else experience this issue?

**Comment by sgiehl** [comment]
Closing this one, as the answer has already been given above.
