### ISSUE TITLE
Error when connecting to Matomo for import_logs.py 

### ISSUE THREAD

**Issue by luigifab38** [matomo-org/matomo-log-analytics#229]
I'm using Matomo's log analyzer 3.6.1 (my Matomo installation works when I use my browser). Since two days, there is an error without information.

```
root@server01:~# python /var/www/piwik/misc/log-analytics/import_logs.py --url=xyz
  --idsite=5 --show-progress --enable-reverse-dns --enable-http-errors
  --useragent-exclude=xyz --exclude-path=/robots.txt
  --exclude-path=*.svg.php /var/log/lighttpd/xyz.access.log.2
2018-11-02 21:27:22,528: [INFO] Error when connecting to Matomo: ''
2018-11-02 21:27:22,528: [INFO] Retrying request, attempt number 2
2018-11-02 21:27:32,564: [INFO] Error when connecting to Matomo: ''
2018-11-02 21:27:32,565: [INFO] Retrying request, attempt number 3
2018-11-02 21:27:42,606: [INFO] Error when connecting to Matomo: ''
2018-11-02 21:27:42,606: [INFO] Max number of attempts reached, server is unreachable!
Traceback (most recent call last):
  File "/var/www/piwik/misc/log-analytics/import_logs.py", line 2626, in <module>
    resolver = config.get_resolver()
  File "/var/www/piwik/misc/log-analytics/import_logs.py", line 1091, in get_resolver
    return StaticResolver(self.options.site_id)
  File "/var/www/piwik/misc/log-analytics/import_logs.py", line 1615, in __init__
    'SitesManager.getSiteFromId', idSite=self.site_id
  File "/var/www/piwik/misc/log-analytics/import_logs.py", line 1598, in call_api
    return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)
  File "/var/www/piwik/misc/log-analytics/import_logs.py", line 1585, in _call_wrapper
    raise Matomo.Error(message, code)
__main__.Error: ''
```

Can you help me?

**Comment by luigifab38** [comment]
I found a thing. I can access to my websites with my browser, but curl can not access to it (with https). I think the problem is something with my ssl certificate by letsencrypt.

**Comment by tsteur** [comment]
You could try and add `--accept-invalid-ssl-certificate`

**Comment by Findus23** [comment]
> You could try and add --accept-invalid-ssl-certificate

Keep in mind that this makes Matomo support insecure connections. You can also test your SSL connection on https://www.ssllabs.com/ or update the CA list of your operating system.

**Comment by luigifab38** [comment]
I try the accept option, same result.
My website is ok with ssllabs.

**Comment by luigifab38** [comment]
But, I have and idea, it seems that TLS 1.0 and 1.1 has been deactivated again (perhaps a Debian testing package update on the server, I will search).

**Comment by Findus23** [comment]
> it seems that TLS 1.0 and 1.1 has been deactivated again

Which isn't such a bad idea.

> but curl can not access to it

What error does curl report?

**Comment by luigifab38** [comment]
curl says: (52) Empty reply from server

**Comment by Findus23** [comment]
Sounds as if this wasn't a HTTP issue, but a firewall or something similar blocking the connection to the server.

**Comment by Findus23** [comment]
You can revert that change by setting `MinProtocol` to `TLSv1` in `/etc/ssl/openssl.cnf`.

**Comment by luigifab38** [comment]
There was an update of curl yesterday and I move tu php-7.3 yesterday. Now the problem is fixed.
